### ISSUE TITLE
"learn more" links from each step of "add a feed" to documentation sections

### ISSUE THREAD

**Issue by souperneon** [transitland/feed-registry#158]

**Comment by drewda** [comment]
will link out to https://github.com/transitland/transitland-docs

**Comment by rmglennon** [comment]
@souperneon - the most relevant topic is https://github.com/transitland/transitland-docs/blob/master/add-feed.md

If you want, each page of the Add a feed flow could have a targeted "Learn more" to a section anchor link in the md file. For example, https://github.com/transitland/transitland-docs/blob/master/add-feed.md#choose-the-transit-operators-in-the-feed (We'd just have to make sure the headings are stable when we link to them to avoid breaking links.)

**Comment by drewda** [comment]
@rmglennon if you want slightly more stable anchors, I think you can probably wrap the headers in `<a id="step2blah"></a>` to lock in the anchor name, instead of using what's auto-generated by GitHub Markdown.

**Comment by meghanhade** [comment]
@souperneon is this still on deck for this week, or should we move it to 'future'?

**Comment by souperneon** [comment]
may have to move this to future… sorry haven't gotten a chance to give it some thought :(

**Comment by meghanhade** [comment]
@souperneon no problem at all.

**Comment by drewda** [comment]
@rmglennon @souperneon let's include some type of links from each step of the process to the docs page for the release. Rather than style a custom element, let me suggest a link at the bottom of each step that reads "Learn More About Operators", "Learn More About License", etc. If you want to be even fancier, it can include a question mark icon from Font Awesome.

@rmglennon how about I open a PR with those links and then you can review and edit?

**Comment by rmglennon** [comment]
:+1: Also makes it so we can send people to the help if they get errors during the process.

Only change I'd have from those is to use sentence case on the words, "Learn more about..." :)

**Comment by drewda** [comment]
@rmglennon please review and edit https://github.com/transitland/feed-registry/pull/223
