### ISSUE TITLE
List of error messages

### ISSUE THREAD

**Issue by meghanhade** [transitland/feed-registry#216]
A list of the possible errors that will be passed to the front end, and their meanings. @rmglennon  will write the display message.

**Comment by irees** [comment]
@rmglennon @meghanhade 

Requests to the /api/v1/feeds/fetch_info endpoint include the URL of the GTFS feed we want to process. The datastore will then try to download the URL and process the data. This can generate a variety of errors, which will be returned in the fetch_info response as an array of objects. Each error has an 'exception' attribute with the name of the exception class, a 'message', and an optional 'response_code'.

## InvalidSourceException
"The file does not appear to be a valid GTFS file."
This error occurs when the file was either 1) not a valid zip file 2) missing required GTFS tables 3) the table files were not CSV or 4) did not contain required columns. Currently these cases are all rolled into 'InvalidSourceException' but could be made finer-grained in the future.

## SocketError
"There was a problem downloading the file. The remote server did not respond."
This occurs when there is a network-level error while trying to download the url; it could be either a bad host name, a network issue, remote server down, remote server not responsive, etc. It's hard to tell the user what to do in this case, because it could be either a problem with their URL or a problem with the agency server.

## HTTPServerException
"There was an error downloading the file. The agency server responded with <...>"
The transit agency server completed the http request but responded with an error, such as 404 not found, 401 not authorized, etc. These types of errors will also include a 'response_code' attribute in the error messages. The most common error response_codes are (and my suggested text):
400 - "Could not process request"
401 / 403 - "Access denied"
404 - "File not found"
500 - "Server error"
502 / 503 - "Server temporarily unavailable"
504 - "Server time-out"

## Other errors
"There was a problem downloading or processing the url."
Finally, there's a catch-all for any other kind of error. The 'exception' will be the name of the ruby exception class in the backend. Perhaps these types of errors should be considered bugs that need to be resolved, or problems with *our* servers. I'm open to discussion on this. 
    
Notes:
https://github.com/transitland/transitland-datastore/blob/master/app/workers/feed_info_worker.rb
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by meghanhade** [comment]
@rmglennon Please add your list of what copy you'd like displayed for each error here and reassign this issue to me (@meghanhade) when it's ready for me to use.

**Comment by rmglennon** [comment]
I think @irees' suggestions are pretty good (thank you!), so just a few little suggestions about where to go to get more help. I'll put some info about this in the docs, too. For future enhancement, we can add those "Learn more" help links and go right to a section on errors.

InvalidSourceException: "This file does not appear to be a valid GTFS feed. Contact Transitland for more help." 

SocketError: "There was a problem downloading the file. Check the address and try again, or contact the transit operator for more help."

HTTPServerException: "There was a problem downloading the file. The server responded with <...>"

"There was a problem downloading or processing from this URL." (maybe something like that?)

**Comment by meghanhade** [comment]
Talking with @irees about just replacing the messages on the back end.

**Comment by drewda** [comment]
@meghanhade lines that you can edit and open your own PR against:

- `InvalidSourceException`: https://github.com/transitland/transitland-datastore/blob/420fda3e24f048d2ab03916d1b1b54f30df20907/app/workers/feed_info_worker.rb#L19
- `SocketError`: https://github.com/transitland/transitland-datastore/blob/420fda3e24f048d2ab03916d1b1b54f30df20907/app/workers/feed_info_worker.rb#L24
- `HTTPServerException`: https://github.com/transitland/transitland-datastore/blob/420fda3e24f048d2ab03916d1b1b54f30df20907/app/workers/feed_info_worker.rb#L29

**Comment by meghanhade** [comment]
@drewda thanks!

**Comment by drewda** [comment]
![feed_registry_ _transitland](https://cloud.githubusercontent.com/assets/212369/12863636/9f575c6c-cc2d-11e5-93bf-a76504cd4c45.png)

![feed_registry_ _transitland](https://cloud.githubusercontent.com/assets/212369/12863640/b4a52ed2-cc2d-11e5-865b-fe953c5c15d4.png)
![feed_registry_ _transitland](https://cloud.githubusercontent.com/assets/212369/12863643/c3036a16-cc2d-11e5-893c-5f3e2b7917c8.png)
