### ISSUE TITLE
incorrectly reporting feeds as existing (was: Are feeds in the process of being validated listed anywhere? Attempt to submit Detroit)

### ISSUE THREAD

**Issue by brendanbabb** [transitland/feed-registry#300]
I encouraged other cities to add their feeds after entering Anchorage's and a friend was searching if Detroit already had a feed, didn't see one listed and attempted to add it and the system responded that it was already in the system.

When a feed is being processed is it listed anywhere? 
When a feed is rejected and the original submitter doesn't respond can some other person submit or edit a rejected feed?

**Comment by drewda** [comment]
@brendanbabb thanks for contributing feeds and for reporting this issue! We're still working on the details of the feed submission, import, and editing cycle. If you're curious to look into outstanding submissions, you can pull up https://transit.land/dispatcher/changesets

@meghanhade please have a look at the existing feed logic next week. Looks like the existing feed/operator message comes up all the time now, since it's just relying on the presence of a `warnings` property: https://github.com/transitland/feed-registry/blob/master/app/feeds/new/add-operator/route.js#L22 Should instead check for an actual message in that array.

**Comment by meghanhade** [comment]
@brendanbabb thanks for reporting this issue! 

@drewda PR #https://github.com/transitland/feed-registry/pull/301 should handle this, if you could please review the fix.

**Comment by drewda** [comment]
@meghanhade sure, this looks good for now. Feel free to deploy to dev and prod, after you've tested with both positive and negative cases.

In the future, it will be worth actually checking the contents of the warning messages--but for now I imagine this is the only warning that @irees is trying to return from the Datastore side.

**Comment by meghanhade** [comment]
@drewda good point. I've merged to production with this fix, but will set up a better check of the warning content next.

**Comment by drewda** [comment]
@meghanhade :+1: and thanks for jumping on this
